POST http://localhost:3003/api/blogs/6694134c1a63120998032ccb/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Iml2YW4iLCJpZCI6IjY2ODI3ZDI1Y2I2ZGU3OWRkOTYwNDcxNSIsImlhdCI6MTcxOTgzMTAyNn0.1-5pmNZJaNRcnmQToUFan1u0T9z2TiGP8aaLzPtXBlk

{
  "content": "comment"
}